nodes:
  - id: 1
    node_name: Mission_Test
    node_type: SEQUENCE
    task: LAND
    parameters: ""
    is_recurrent: true
    activate: true
    parent: 0
  - id: 2
    node_name: Take_Off
    node_type: TASK
    task: TAKE_OFF
    parameters: ""
    is_recurrent: false
    activate: false
    parent: 1
  - id: 3
    node_name: Map
    node_type: REPEATER
    task: LAND
    parameters: "n: 3"
    is_recurrent: false
    activate: false
    parent: 1
  - id: 4
    node_name: Waypoint 1
    node_type: TASK
    task: FOLLOW_PATH
    parameters: "path: [ [0,0,-4], [3, 0, -4], [3, 11, -4], [1.5, 11, -4], [1.5,0,-4],[0,0,-4] ]"
    is_recurrent: false
    activate: false
    parent: 3